"""init

Revision ID: 3d8207618ebf
Revises: 
Create Date: 2021-10-25 15:18:29.694274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d8207618ebf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_account',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('virtual_account', sa.String(length=18), nullable=False),
    sa.Column('company_code', sa.Integer(), nullable=False),
    sa.Column('expired', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('virtual_account', name=op.f('pk_virtual_account'))
    )
    op.create_table('payment',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('reference', sa.String(length=15), nullable=False),
    sa.Column('company_code', sa.String(length=5), nullable=False),
    sa.Column('customer_number', sa.String(length=18), nullable=False),
    sa.Column('request_id', sa.String(length=30), nullable=False),
    sa.Column('channel_type', sa.String(length=4), nullable=False),
    sa.Column('customer_name', sa.String(length=30), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('paid_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('sub_company', sa.String(length=5), nullable=True),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('flag_advide', sa.String(length=1), nullable=False),
    sa.Column('additional_data', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['customer_number'], ['virtual_account.virtual_account'], name=op.f('fk_payment_customer_number_virtual_account')),
    sa.PrimaryKeyConstraint('reference', name=op.f('pk_payment'))
    )
    op.create_table('transaction',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('trx_id', sa.Text(), nullable=False),
    sa.Column('customer_number', sa.String(length=18), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('customer_name', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('callback_url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=1), server_default='0', nullable=False),
    sa.Column('expired_in_second', sa.Integer(), nullable=False),
    sa.Column('payment_ref', sa.String(length=15), nullable=True),
    sa.ForeignKeyConstraint(['customer_number'], ['virtual_account.virtual_account'], name=op.f('fk_transaction_customer_number_virtual_account')),
    sa.ForeignKeyConstraint(['payment_ref'], ['payment.reference'], name=op.f('fk_transaction_payment_ref_payment')),
    sa.PrimaryKeyConstraint('trx_id', name=op.f('pk_transaction'))
    )
    op.create_table('callback_log',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('trx_id', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('body', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('header', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response_time', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trx_id'], ['transaction.trx_id'], name=op.f('fk_callback_log_trx_id_transaction')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_callback_log'))
    )
    op.create_table('client_log',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('trx_id', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('header', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cookie', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('request', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response_time', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trx_id'], ['transaction.trx_id'], name=op.f('fk_client_log_trx_id_transaction')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_client_log'))
    )
    op.create_table('server_log',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('trx_id', sa.Text(), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('header', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('cookie', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('request', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('response_time', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trx_id'], ['transaction.trx_id'], name=op.f('fk_server_log_trx_id_transaction')),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_server_log'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('server_log')
    op.drop_table('client_log')
    op.drop_table('callback_log')
    op.drop_table('transaction')
    op.drop_table('payment')
    op.drop_table('virtual_account')
    # ### end Alembic commands ###
