"""fix expired

Revision ID: 50e339ad464e
Revises: 70c6000b6011
Create Date: 2021-10-26 01:10:26.695218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e339ad464e'
down_revision = '70c6000b6011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('expired', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'expired')
    # ### end Alembic commands ###
