"""fix callback

Revision ID: 70c6000b6011
Revises: fa2dcf27c553
Create Date: 2021-10-26 00:44:27.703004

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '70c6000b6011'
down_revision = 'fa2dcf27c553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callback_log', sa.Column('request', postgresql.JSON(astext_type=sa.Text()), nullable=False))
    op.alter_column('callback_log', 'response',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('callback_log', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('callback_log', sa.Column('body', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('callback_log', 'response',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('callback_log', 'request')
    # ### end Alembic commands ###
