"""fix typo

Revision ID: 888a30f55f40
Revises: 3d8207618ebf
Create Date: 2021-10-25 23:42:52.919850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888a30f55f40'
down_revision = '3d8207618ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('flag_advice', sa.String(length=1), nullable=False))
    op.drop_column('payment', 'flag_advide')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('flag_advide', sa.VARCHAR(length=1), autoincrement=False, nullable=False))
    op.drop_column('payment', 'flag_advice')
    # ### end Alembic commands ###
